import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import CommerceLayerAuth from "@/components/CommerceLayerAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clientId = process.env.CL_CLIENT_ID;
  const market = parseFloat(process.env.CL_MARKET || "0");
  const slug = process.env.CL_SLUG;

  if (!clientId || !market || !slug) {
    throw new Error(
      "You need to set the CL_CLIENT_ID and CL_MARKET environment variables.",
    );
  }

  return (
    <html lang="en">
      <body>
        <CommerceLayerAuth clientId={clientId} market={market} slug={slug}>
          <Header />
          {children}
        </CommerceLayerAuth>
      </body>
    </html>
  );
}
